# CASA0007 
## Practical 4: Linear Algebra</h1>
<div style="float:right"><img width="100" src="https://github.com/jreades/i2p/raw/master/img/casa_logo.jpg" /></div>

## Welcome!

In this practical, we will apply some techniques from linear algebra: 

- Systems of equations 
- Matrix operations 

In [1]:
# import relevant packages

import numpy as np
# 3d plotting tools
import plotly.graph_objects as go

## Background

A factory specialises in producing parts for bicycles: handlebars, brakes and wheels. 

- $x_1$ — the number of handlebars they can make  
- $x_2$ — the number of brakes they can make 
- $x_3$ — the number of wheels they can make

These require resources to be made: aluminium, rubber and paint. 

For **each handlebar** they need 8 units of aluminium, 4 units of rubber and 4 units of paint. 
For **each brake** they need 1 unit of aluminium, 1 unit of rubber and 1 unit of paint. 
For **each wheel** they need 10 units of aluminium, 23 units of rubber, and 5 units of paint. 
§

The factory is having problems with the supply of raw materials. On a given day they have: 
- $b_1=400$ units of aluminium,  
- $b_2=750$ units of rubber,  
- $b_3=200$ units of paint.  

What is the optimal number of each bike part  that they can produce?  

## Linear equations  

We can express the resource constraints as a system of equations. If they are producing $x_1, x_2, x_3$ units of each part we need:

$$
8x_1 + x_2 + 10x_3
$$

of aluminium. 

$$
4x_1 + x_2 + 23x_3
$$

of rubber. 

$$
4x_1 + x_2 + 5x_3
$$

of paint. 

Given the contraints of raw materials we can have: 

$$
8x_1 + x_2 + 10x_3 = b_1 = 400
\\
4x_1 + x_2 + 23x_3 = b_2 = 750
\\
4x_1 + x_2 + 5x_3 = b_3 = 200
$$

## Matrix form

This can be written compactly as:

$$
\begin{pmatrix}
8 & 1 & 10 \\
4 & 1 & 23 \\
4 & 1 & 5
\end{pmatrix}
\begin{pmatrix}x_1\\x_2\\x_3\end{pmatrix}
=
\begin{pmatrix}b_1\\b_2\\b_3\end{pmatrix}.
$$

That is, 
$$
M\bar{x} =b 
$$

Where $M$ is the coefficient matrix, 

$$
M = 
\begin{pmatrix}
8 & 1 & 10 \\
4 & 1 & 23 \\
4 & 1 & 5
\end{pmatrix}
$$

$\bar{x}$ is the vector of the number of each part, i.e. the variable sin our equation:

$$
\bar{x} = \begin{pmatrix}x\\y\\z\end{pmatrix}
$$

and $b$ is the resource constraint: 

$$
b = \begin{pmatrix}b_1\\b_2\\b_3\end{pmatrix}.
$$

In [2]:
# written in python as: 

# Coefficient matrix
# M 
M = np.array([[8, 1, 10],
              [4, 1, 23],
              [4, 1, 5]], dtype=float)

# Resource availability
# [b_1, b_2, b_3]
b = np.array([400, 750, 200], dtype=float)  

We can use in-built functions in Python to solve the system of linear equations. The library `np.linalg` provides us with all the matrix operations we need. 

First lets check the determinant of M is non-zero. 

In [3]:
# Calculate the determinant of M
det_M = np.linalg.det(M)
print(det_M)

-71.99999999999994


The det(M) is non-zero! This means that matrix M is invertible. 

Now let's calculate the inverse of M.

```Remember: The inverse of a matrix M is denoted M^-1 and has the property that M * M^-1 = I, where I is the identity matrix.```

In [4]:
# Invert M

M_inv = np.linalg.inv(M)
print(M_inv)

[[ 0.25       -0.06944444 -0.18055556]
 [-1.          0.          2.        ]
 [-0.          0.05555556 -0.05555556]]


Check that $MM^{-1}= I$, where I is the 3x3 identity matrix: 

$$
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$$

In [5]:
# Multiply A by its inverse
MM_inv = np.dot(M, M_inv)
print(MM_inv)

[[ 1.00000000e+00 -5.55111512e-17  5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00 -2.77555756e-17]
 [ 0.00000000e+00 -2.77555756e-17  1.00000000e+00]]


Ok, it's not quite the identity matrix (that's because we are using floating point values in `Python` - which means there's always going to be a small error - i.e. epsilon -  $\epsilon$) 

Rounding the matrix we see that it is very close to the identity.

In [6]:
print(MM_inv.round(2))

[[ 1. -0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


It's the identity matrix!

Now we can solve to find b!

In [7]:
# do M^-1 * b to get x
x = np.dot(M_inv, b)
print(x)

[11.80555556  0.         30.55555556]


Alternatively we can solve the equations using `numpy`s linear algebra solver, which skips most of the steps. 

In [8]:
## Solve the equations using numpy's linear algebra solver
x = np.linalg.solve(M, b)
print(np.round(x, 2))

[11.81 -0.   30.56]


We can also plot the equations in 3D space. Where the 3 planes intersect is our solution!

In [9]:
# Define grid for x1 (handlebars) and x2 (brakes)
x1 = np.linspace(0, 30, 50)
x2 = np.linspace(0, 30, 50)
X1, X2 = np.meshgrid(x1, x2)

# Constraint surfaces (solving for x3 = wheels)
Z_al = (b[0] - 8*X1 - 1*X2) / 10 # from aluminium
Z_rb = (b[1] - 4*X1 - 1*X2) / 23 # from rubber
Z_pn = (b[2] - 4*X1 - 1*X2) / 5 # from paint

# Interactive 3D plot
fig = go.Figure()

fig.add_surface(x=x1, y=x2, z=Z_al, opacity=0.5, colorscale="Blues", name="Aluminium")
fig.add_surface(x=x1, y=x2, z=Z_rb, opacity=0.5, colorscale="Oranges", name="Rubber")
fig.add_surface(x=x1, y=x2, z=Z_pn, opacity=0.5, colorscale="Greens", name="Paint")

# Add solution point
fig.add_trace(go.Scatter3d(x=[x[0]], y=[x[1]], z=[x[2]],
mode="markers", marker=dict(size=6, color="red"),
name="Solution"))

fig.update_layout(
scene=dict(
xaxis_title="Handlebars",
yaxis_title="Brakes",
zaxis_title="Wheels"
))

fig.show()

## Extension 

Try and implement an OLS regression for the data. Image that instead of having equatiosn for the factory we have a data points for a year telling us how many parts they were able to make. 

In [10]:
import numpy as np
import pandas as pd

# Coefficient matrix (resources required per product)
M = np.array([
    [8, 1, 10],   # aluminium consumption
    [4, 1, 23],   # rubber consumption
    [4, 1, 5]     # paint consumption
], dtype=float)

# Resource availability (baseline example)
b = np.array([400, 750, 200], dtype=float)

# Number of synthetic samples
n = 365

# Randomly generate production levels (handlebars x1, brakes x2, wheels x3)
np.random.seed(42)
x1 = np.random.randint(0, 40, size=n)
x2 = np.random.randint(0, 40, size=n)
x3 = np.random.randint(0, 40, size=n)
X = np.vstack([x1, x2, x3]).T

# Compute resources consumed
y_true = X @ M.T  # shape (n,3): [Aluminium, Rubber, Paint]

# Add Gaussian noise to simulate measurement error
y_obs = y_true + np.random.normal(0, 10, size=y_true.shape)

# Build DataFrame
df = pd.DataFrame({
    "x1_handlebars": x1,
    "x2_brakes": x2,
    "x3_wheels": x3,
    "aluminium_used": y_obs[:,0],
    "rubber_used": y_obs[:,1],
    "paint_used": y_obs[:,2]
})

df.head()

# Save to CSV
outpath = "factory_data.csv"
df.to_csv(outpath, index=False)
print(f"Synthetic dataset saved to {outpath}")

Synthetic dataset saved to factory_data.csv


In [12]:
# solve for production levels given observed resource usage for x_1
# using statsmodels OLS regression

import statsmodels.api as sm
import pandas as pd 
# load synthetic dataset
df = pd.read_csv("factory_data.csv")
# define independent variables (resources used)
X = df[["aluminium_used", "rubber_used", "paint_used"]]
# add constant term for intercept
X = sm.add_constant(X)
# define dependent variable (production of handlebars)
y = df["x1_handlebars"]
# fit OLS regression model
model = sm.OLS(y, X).fit()
# print model summary
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:          x1_handlebars   R-squared:                       0.974
Model:                            OLS   Adj. R-squared:                  0.974
Method:                 Least Squares   F-statistic:                     4477.
Date:                Thu, 16 Oct 2025   Prob (F-statistic):          3.99e-285
Time:                        14:42:08   Log-Likelihood:                -754.52
No. Observations:                 365   AIC:                             1517.
Df Residuals:                     361   BIC:                             1533.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const             -1.3429      0.278     -4.

## Conclusions 

Here we solved a set of linear equations using algebra. 

## Extension 

## Credits
### Contributors:
The following individuals have contributed to these teaching materials: [Bea Taylor](https://github.com/Bea-Taylor)

### License
These teaching materials are licensed under a mix of The MIT License and the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license.

### Acknowledgements
NA

### Dependencies
This notebook depends on the following libraries: numpy and plotly